name = "leshooflad"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
account_id = '891d3a91fc63b613f18c8fc05a6c843f'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-06-24"
kv_namespaces = [
    { binding = "CONTENT", id = "0cd7ed7905ac4394b99cd8a50ba7d737", preview_id = "f50f4dbbda5848dea8dbfcca8fdd6535" }
]

[site]
bucket = "./public"
entry-point = "workers-site"

# Lets you call Workers periodically, much like a cron job.
# More details: https://developers.cloudflare.com/workers/platform/cron-triggers
# @default `{crons:[]}`
[triggers]
crons = ["*/10 * * * *"]

# https://developers.cloudflare.com/workers/wrangler/cli-wrangler/commands/#kv
[env.dev]
kv_namespaces = [
    { binding = "CONTENT", id = "0cd7ed7905ac4394b99cd8a50ba7d737", preview_id = "f50f4dbbda5848dea8dbfcca8fdd6535" }
]